### ISSUE TITLE
Properties added in deserialization doesn't exist in resolved value from promise

### ISSUE THREAD

**Issue by hinok** [jmdobry/angular-data#286]
Hey,
It would be great if I could expose headers in objects returned from API.
I thought that deserialize() will help in that case but dunno it doesn't.

```javascript
// inside config
DSProvider.defaults.deserialize = function(resourceName, data) {
    if (data.data) {
        if (typeof data.headers === 'function') {
            // It appends headers correctly here
            data.data.$headers = date.headers();
        }
        return data.data;
    }

    return data;
  };
```

Then somewhere in code

```javascript
User.findAll().then(function(promoters) {
  promoters.$headers // is undefined, there is no $headers in that object / array
});
```

Now I'm passing headers with help of promises (like https://github.com/jmdobry/angular-data/issues/183 passing callback here) but I think that simple property is better for things like this.

Related: https://github.com/jmdobry/angular-data/issues/183

**Comment by jmdobry** [comment]
Your example doesn't work because `data.data` is an array, and when the items in the array are injected into the they are injected one by one into the store's array, and the `data.data` array is discarded. If you want any meta data saved, you either need to store it in some other data structure that you control, or put the data on the individual items themselves.

```js
DSProvider.defaults.deserialize = function(resourceName, data) {
  if (data.data) {
    if (typeof data.headers === 'function') {
      // It appends headers correctly here
      var headers = data.headers();
      if (angular.isArray(data.data)) {
        angular.forEach(data.data, function (item) {
          item.$headers = headers;
        });
      } else {
        data.data.$headers = headers;
      }
    }
    return data.data;
  }
  return data;
};
```

**Comment by hinok** [comment]
Thank you @jmdobry for fast reply!

It took me an hour to figure out that `data.headers()` from $http service returns object created by using Object.create(null). There is no prototype!

As the result I was getting this errors:

```
TypeError: undefined is not a function
    at copy (http://localhost:8000/bundle.js:10400:20)
    at copy (http://localhost:8000/bundle.js:10361:23)
    at copy (http://localhost:8000/bundle.js:10401:20)
    at Object.copy (http://localhost:8000/bundle.js:10361:23)
    at Object._inject (http://localhost:8000/bundle.js:45317:53)
    at Object.inject (http://localhost:8000/bundle.js:45458:24)
    at http://localhost:8000/bundle.js:41763:25
    at processQueue (http://localhost:8000/bundle.js:22741:27)
    at http://localhost:8000/bundle.js:22757:27
    at Scope.$get.Scope.$eval (http://localhost:8000/bundle.js:23954:28)
bundle.js:21165 inject failed! socialprovider Object {...}
```

**Solution**

```
DSProvider.defaults.deserialize = function(resourceName, data) {
    var headers;

    /**
     * angular function data.headers() returns an object created by
     * using Object.create(null) which doesn't have set prototype to Object
     * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Example:_Using_propertiesObject_argument_with_Object.create
     * @param {Object} source - Plain JavaScript object without prototype set to Object
     * @returns {Object} Returns a copy of object with prototype set to Object
     */
    var copy = function(source) {
      var dest = {};
      for (var prop in source) {
        dest[prop] = source[prop];
      }
      return dest;
    };

    if (data.data) {
      if (typeof data.headers === 'function') {
        headers = copy(data.headers());

        if (angular.isArray(data.data)) {
          angular.forEach(data.data, function(item) {
            item.$headers = headers;
          });
        } else {
          data.data.$headers = headers;
        }
      }

      return data.data;
    }

    return data;
  };
```
