### ISSUE TITLE
is the syntax for bindAll has changed?

### ISSUE THREAD

**Issue by doobleweb** [jmdobry/angular-data#302]
the get ReadMe says it should be
Message.bindAll($scope, 'comments', query);

but in really it is
Message.bindAll({}, $scope, 'ctrl.messages');

**Comment by jmdobry** [comment]
Can you be more specific where it says what?

**Comment by doobleweb** [comment]
off course

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script src="/angular.js"></script>
	<script src="/js-data.js"></script>
	<script src="/js-data-localstorage.js"></script>
	<script src="/js-data-angular.js"></script>	
	<script>
		var app = angular.module('app', ['js-data']);
		app.run(function (DS, Message) {
			DS.registerAdapter('localstorage', DSLocalStorageAdapter, { default: true });
		});

		app.factory('Message', function(DS){
			return DS.defineResource('message');
		});

		app.controller('ctrl', function ($scope, Message) {
			$scope.test = 'test';

			Message.bindAll($scope, 'messages', {});
		});
	</script>
</head>
<body ng-app="app" ng-controller="ctrl">
	<h1>{{messages | json}}</h1>
</body>
</html>
```

```js
Error: "scope" must be an object!
    at DS.angular.module.value.value.provider.JSData.DS.bindAll (http://localhost:8080/js-data-angular.js:134:17)
    at Defaults.36.def.(anonymous function) [as bindAll] (http://localhost:8080/js-data.js:3585:29)
    at new <anonymous> (http://localhost:8080/:23:12)
    at Object.invoke (http://localhost:8080/angular.js:4182:17)
    at $get.extend.instance (http://localhost:8080/angular.js:8445:21)
    at http://localhost:8080/angular.js:7697:13
    at forEach (http://localhost:8080/angular.js:331:20)
    at nodeLinkFn (http://localhost:8080/angular.js:7696:11)
    at compositeLinkFn (http://localhost:8080/angular.js:7075:13)
    at publicLinkFn (http://localhost:8080/angular.js:6954:30)
```

**Comment by jmdobry** [comment]
Ah yes, the syntax for `bindOne` and `bindAll` did change between 1.x and 2.x. It's noted [here](https://github.com/jmdobry/angular-data/pull/198), though I forgot to document the new `bindOne`, `bindAll` API [here](http://www.js-data.io/v1.0.0-beta.1/docs/js-data-angular).
